import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

 import {HeaderMobileTypeOne,NavMobileTypeOne} from "componentes-dengel" 
import { useState } from 'react'
import "componentes-dengel/dist/style.css" 

export default function Home() {

const[openMenu,setOpenMenu]=useState(false)

  return (

    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderMobileTypeOne
      setOpenMenu={()=>setOpenMenu(!openMenu)}
      openMenu={openMenu}
      colorHeader="bg-blue-700"
      logo={<Link href='/'><Image width={30} height={30} alt='image'  src={'next.svg'}/></Link>}
      > 
        
     <NavMobileTypeOne openMenu={openMenu}>
          <Link className='text-white' href={"#"}>Contactos</Link>
          <Link className='text-white' href={"#"}>Contactos</Link>
        </NavMobileTypeOne>
      </HeaderMobileTypeOne> 
    
      <main className=''>
     <h2>hola</h2>
     
      </main>
    </div>
  )
}
