import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {HeaderTwo,NavDesktopTypeTwo,NavMobileTypeTwo} from "componentes-dengel" 
import { useState } from 'react'
import "componentes-dengel/dist/style.css" 
import NavDesktop from '../components/NavDesktop'
import LinkNav from '../components/LinkNav'
import IconHome from '../components/Icons/IconHome'
import IconJob from '../components/Icons/IconJob'
import IconBlog from '../components/Icons/IconBlog'
import IconBrochure from '../components/Icons/IconBrochure'
import IconPlantilla from '../components/Icons/IconPlantilla'
import IconModule from '../components/Icons/IconModule'
import LinkNavLittleDesktop from "../components/LinkNavLittleDesktop"
import SitiosWeb from '../components/SitiosWeb'
export default function Home() {

const[openMenu,setOpenMenu]=useState(false)
const[openMenuDesktop,setOpenMenuDesktop]=useState(false)
  return (

    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      
      </Head>
    
      <HeaderTwo 
      posicion="lg:justify-center" logo={<Link href='/'><Image width={30} height={30} alt='image'  src={'next.svg'}/></Link>} LinksNavDesktop={<NavDesktop/>} colorHeader='bg-gradient-to-t from-primary via-secundary to-secundary ' openMenuDesktop={openMenuDesktop}  openMenu={openMenu} 
      
      navDesktopLittle={<NavDesktopTypeTwo colorNavLittleDesktop={"bg-whiteTransparent3 backdrop-blur"} openMenuDesktop={openMenuDesktop}>
      <LinkNavLittleDesktop href="#" Icon={<IconBrochure/>} text="Mi brochure"/>
      <LinkNavLittleDesktop href="#" Icon={<IconBlog/>} text="Mi blog"/>
      <LinkNavLittleDesktop href="#" Icon={<IconPlantilla/>} text="Mis plantillas web premium"/>
  </NavDesktopTypeTwo>} 
  setOpenMenu={()=>{setOpenMenu(!openMenu)}} 
  setOpenMenuDesktop={()=>{setOpenMenuDesktop(!openMenuDesktop)}}>
    
    <NavMobileTypeTwo colorNavMobile={"bg-whiteTransparent3 backdrop-blur"} openMenu={openMenu}>
    <LinkNav Icon={ <IconHome/>} text={" Mi punto de partida"} href={"#"}/>
        <LinkNav Icon={ <IconModule/>} text={" Mis servicios integrales"} href={"#"}/>
        <LinkNav Icon={ <IconJob/>} text={" Mi repositorio de proyectos"} href={"#"}/>
        <LinkNav Icon={ <IconBrochure/>} text={"Mi brochure"} href={"#"}/>
        <LinkNav Icon={ <IconBlog/>} text={"Mi brog"} href={"#"}/>
        <LinkNav Icon={ <IconPlantilla/>} text={"Mis plantillas web premium"} href={"#"}/>
    </NavMobileTypeTwo>

    
    </HeaderTwo>
    
      <main className='bg-gradient-to-t from-secundary2 via-secundary3 to-secundary3 ' >
   
   {/*   <section className='bg-gradient-to-t from-primary via-secundary to-secundary h-auto rounded-bl-[36px] rounded-br-[90px] overflow-hidden xl:h-[586px] '>
      <h2 className={styles.textPresent}>Creo apps efectivas con diseño y codificación de calidad</h2>
     </section> */}
     <section className={styles.fondo}>
     <h2 className={styles.textPresent}>Creo apps efectivas con diseño y codificación de calidad</h2>
     <article className={styles.seccion}>
      <p className='pt-[55px] pb-[80px] pr-[16px] pl-[16px]'>Te ayudo a alcanzar tus objetivos de manera rápida y eficiente con nuestros servicios efectivos</p>
     </article>

     <article className='p-[16px] mt-[21px] mb-[21px]'>
     <button className='bg-yellow1 font-Roboto font-extrabold text-[16px] text-center w-[328px] text-blue1 pt-[10px] pb-[10px] rounded-tl-2xl rounded-tr-2xl rounded-bl-2xl rounded-br-2xl'>Conoce más</button>
     </article>

     <article className='pl-[16px] pr-[16px] pb-[50px]'>
     <SitiosWeb/>
     </article>
  
     </section>
     <h2>hola</h2>
     
      </main>
    </div>
  )
}
