import ContenidoBlog from "../components/miblog/ContenidoBlog"
export const publicaciones=[
    {imagen:"https://res.cloudinary.com/darps1cta/image/upload/v1681937216/sitioweb/Los_beneficios_de_usar_Shopify_para_crear_tu_tienda_en_l%C3%ADnea_xj2mub.jpg",
    categoria:"Tienda virtual shopify",
titulo:"Los beneficios de usar Shopify para crear tu tienda en línea",
url:'benificios-crear-tienda-shopify',
parrafo:<ContenidoBlog markdown='contenido_01.md'/>},
{imagen:"https://res.cloudinary.com/darps1cta/image/upload/v1681937215/sitioweb/C%C3%B3mo_elegir_el_tema_adecuado_para_tu_tienda_Shopify_mfaper.jpg",
categoria:"Tienda virtual shopify",
titulo:"Cómo elegir el tema adecuado para tu tienda Shopify",
url:'elegir-tema-shopify',
parrafo:<ContenidoBlog markdown='contenido_02.md'/>},
{imagen:"https://res.cloudinary.com/darps1cta/image/upload/v1681937417/sitioweb/Pasos_para_optimizar_la_velocidad_de_carga_de_tu_tienda_Shopify_fdxzwg.jpg",
categoria:"Optimización",
titulo:"Pasos para optimizar la velocidad de carga de tu tienda Shopify",
url:'optimizar-tienda-shopify',
parrafo:<ContenidoBlog markdown='contenido_03.md'/>},
{imagen:"https://res.cloudinary.com/darps1cta/image/upload/v1681937215/sitioweb/C%C3%B3mo_integrar_tu_tienda_Shopify_con_redes_sociales_y_otras_plataformas_de_venta_pihgyf.jpg",
categoria:"Tienda virtual shopify",
titulo:"Cómo integrar tu tienda Shopify con redes sociales y otras plataformas de venta",
url:'intergrar-redes-sociales-otras-plataformas',
parrafo:<ContenidoBlog markdown='contenido_04.md'/>},
]
export const publicaciones_populares=[
    {imagen:"https://res.cloudinary.com/darps1cta/image/upload/v1681937216/sitioweb/5_aplicaciones_de_Shopify_que_no_te_puedes_perder_para_tu_tienda_virtual_vq6zzb.jpg",
    categoria:"Tienda virtual shopify",
    titulo:"5 aplicaciones de Shopify que no te puedes perder para tu tienda virtual",
    url:'5-aplicaciones-shopify',
    parrafo:<ContenidoBlog markdown='contenido_05.md'/>},
    {imagen:"https://res.cloudinary.com/darps1cta/image/upload/v1681937216/sitioweb/5_razones_por_las_que_tu_negocio_necesita_una_tienda_virtual_en_Shopify_elugcl.jpg",
    categoria:"Tienda virtual shopify",
    titulo:"5 razones por las que tu negocio necesita una tienda virtual en Shopify",
    url:'5-razones-por-las-que-tu-negocio-necesita-una-tienda-virtual-en-Shopify',
    parrafo:<ContenidoBlog markdown='contenido_06.md'/>}, 
]