import ContenidoBlog from "../components/miblog/ContenidoBlog"
export const publicaciones=[
    {imagen:"https://res.cloudinary.com/darps1cta/image/upload/v1679615808/sitioweb/hombre-adulto-haciendo-compras-linea-dia-ocio-casa-joven-comprando-ropa-online_uuxpql.jpg",
    categoria:"negociacion",
titulo:"Los beneficios de usar Shopify para crear tu tienda en línea",
url:'proceso-nego',
parrafo:<ContenidoBlog markdown='contenido_01.md'/>},
{imagen:"https://res.cloudinary.com/darps1cta/image/upload/v1679615808/sitioweb/hombre-adulto-haciendo-compras-linea-dia-ocio-casa-joven-comprando-ropa-online_uuxpql.jpg",
categoria:"negociacion2",
titulo:"Proceso de negociación: Domina y cierra mas tratos",
url:'proceso-nego2'},
{imagen:"https://res.cloudinary.com/darps1cta/image/upload/v1679615808/sitioweb/hombre-adulto-haciendo-compras-linea-dia-ocio-casa-joven-comprando-ropa-online_uuxpql.jpg",
categoria:"negociacion4",
titulo:"Proceso de negociación: Domina y cierra mas tratos",
url:'proceso-nego3'},
{imagen:"https://res.cloudinary.com/darps1cta/image/upload/v1679615808/sitioweb/hombre-adulto-haciendo-compras-linea-dia-ocio-casa-joven-comprando-ropa-online_uuxpql.jpg",
categoria:"negociacion",
titulo:"Proceso de negociación: Domina y cierra mas tratos",
url:'proceso-nego4'},
]
export const publicaciones_populares=[
    {imagen:"https://res.cloudinary.com/darps1cta/image/upload/v1679615808/sitioweb/hombre-adulto-haciendo-compras-linea-dia-ocio-casa-joven-comprando-ropa-online_uuxpql.jpg",
    categoria:"negociacion4",
    titulo:"Proceso de negociación: Domina y cierra mas tratos",
    url:'proceso-nego3'},
    {imagen:"https://res.cloudinary.com/darps1cta/image/upload/v1679615808/sitioweb/hombre-adulto-haciendo-compras-linea-dia-ocio-casa-joven-comprando-ropa-online_uuxpql.jpg",
    categoria:"negociacion",
    titulo:"Proceso de negociación: Domina y cierra mas tratos",
    url:'proceso-nego4'}, 
]